### ISSUE TITLE
Embedded iframe is not editable

### ISSUE THREAD

**Issue by dholakiyaankit** [square/square-market-embeds#11]
Hey, I have embed your code into my site. all is working fine. but my client reported me that the website is creating problems in his Iphone when I have a drop-down.

I just wanna use select2.js into iframe so it will render thee drop-downs as it is into mobile as well.

Can you help me anyway that I can add my necessary links into that iframe popup which is appearing in the embedded items?

**Comment by dholakiyaankit** [comment]
Anyone who can help me?

**Comment by keithchu** [comment]
We don't currently support editing of the content inside the embed.

**Comment by dholakiyaankit** [comment]
@keithchu  thanks for your reply.

Is there any way I can achieve?

**Comment by dholakiyaankit** [comment]
@keithchu  is there any 1% chance that I can achieve this?

**Comment by keithchu** [comment]
I don't understand what you're trying to do well enough to think of a workaround. Do you have an example link that shows the issue clearly?

**Comment by dholakiyaankit** [comment]
@keithchu http://exxpo.io/drink look at the items there. What i want is I want to change the content of that iframe anyhow. Client told me that the contents doesn't looks good in mobile so I want to change the css or need to add css there in Iframe.

**Comment by keithchu** [comment]
@dholakiyaankit It looks like you're using Squarespace and not using the Square Market embeds. I recommend getting in contact with them for your support needs.
