### ISSUE TITLE
embedding a series of items

### ISSUE THREAD

**Issue by thvv** [square/square-market-embeds#8]
I am trying to generate a gallery page.  In the simple file http://multicians.org/thvv/sqtest1.html, I embed 6 items.  5 fit on a line in my window. The 6th item goes to a new row that overlaps the row above. 
I observe this with Firefox 37, Chrome 42, Safari 7.1.5 on a Mac, 
http://multicians.org/thvv/sqtest2.html tries to fix this by breaking the container div into two
and inserting an unrelated item.  doesn't help.

**Comment by keithchu** [comment]
Is this still an issue? Neither of the above repro links are working at the moment.

**Comment by keithchu** [comment]
Closing.
