### ISSUE TITLE
masonry example nonportable

### ISSUE THREAD

**Issue by thvv** [square/square-market-embeds#9]
minor issue.
I viewed http://square.github.io/square-market-embeds/example-masonry/index.html and did a "save as HTML."  Opening the file produces different layout: each item starts at the left margin.
Turns out that near the bottom, index.html embeds a file by relative URL.  Suggest you change this from "masonry.pkgd.min.js" to 
"http://square.github.io/square-market-embeds/example-masonry/masonry.pkgd.min.js".

**Comment by keithchu** [comment]
Updated. Thanks for the heads up.

**Comment by thvv** [comment]
keith, i have no idea why you are sending me this mail.

**Comment by keithchu** [comment]
I think Github automatically sent it.

https://github.com/square/square-market-embeds/issues/9#issuecomment-134324511 https://github.com/square/square-market-embeds/issues/9#issuecomment-134324511

**Comment by thvv** [comment]
I can see that, but why?  I have never heard of square-market-embeds.  
I am not a contributor or a member.  I am not watching the project.
notifications@github.com (github-smtp2-ext8.iad.github.net) must be broken.
I will try unsubscribing, and failing that I will plonk github.com.
